/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package album;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author feliciano07
 */
public class VentanaUsuarios extends javax.swing.JFrame {
    public static NodoUsuarios activo;
    public static Nodo_Equipo equipo;
    public static Nodo_Jugador jugador;
    
    //MANIPULAR ESTAMPAS Que se van abriendo
    public static NodoSobre actual;
    public static Nodo_Estam estampa;
    public static String Ruta;
    public static String nombre;
    public static Integer Codigo;
    
    //MANIPULACION ESTAMPAS QUE CONTIENE EL USUARIO
    public static NodoSobre sobres;
    public static Nodo_Estam estampas;
    //MANIPULACION ESTAMPAS 
    public static NodoSobre sobres1;
    public static Nodo_Estam estampas1;
    
    //MANIPULACION DEL ALBUM COMO TAL
    public static Nodo_Jugador jugadores1;
    public static Nodo_Equipo equipos;
    public static String nombreEquipo;
    public static String nombreJugador;
    public static String imagen;
    
    /**
     * Creates new form VentanaUsuarios
     * @param activo
     */
    public VentanaUsuarios(NodoUsuarios activo) {
        VentanaUsuarios.activo=activo;
        VentanaUsuarios.Ruta="";
        VentanaUsuarios.nombre="";
        
        
        
        
        
        initComponents();
        this.TotalSobres.setText("Sobres Abiertos: "+VentanaUsuarios.activo.getAbiertos());
        this.TotalEstampasColocadas.setText("Estampas Colocadas: "+VentanaUsuarios.activo.getColocadas());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecienAbierto = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        MostrarEstampa = new javax.swing.JLabel();
        Siguiente = new javax.swing.JButton();
        InformacionEstampa = new javax.swing.JLabel();
        ColocarRecienAbierto = new javax.swing.JButton();
        MostrarSyE = new javax.swing.JDialog();
        Sobres = new javax.swing.JLabel();
        SobreSiguiente = new javax.swing.JButton();
        SobreAnterior = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ImagenSobre = new javax.swing.JLabel();
        EstampaSiguiente1 = new javax.swing.JButton();
        ColocarEstampa2 = new javax.swing.JButton();
        InformacionEstampa1 = new javax.swing.JLabel();
        MostrarSoloEstampas = new javax.swing.JDialog();
        MostrarEstampa2 = new javax.swing.JLabel();
        EstampaSiguiente = new javax.swing.JButton();
        ColocarEstampa3 = new javax.swing.JButton();
        InformacionEstampa2 = new javax.swing.JLabel();
        AlbumUsuario = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        MostrarJugadores = new javax.swing.JLabel();
        NombreDeEquipos = new javax.swing.JLabel();
        EquipoSiguiente = new javax.swing.JButton();
        EquipoAnterior = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        JugadorSiguiente = new javax.swing.JButton();
        JugadorAnterior = new javax.swing.JButton();
        NombreDelJugador = new javax.swing.JLabel();
        SobreDorado = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ImagenDorada = new javax.swing.JLabel();
        InformacionDorada = new javax.swing.JLabel();
        SiguienteDorada = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        VentanaInter = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        EstampaInter = new javax.swing.JLabel();
        InterSiguiente = new javax.swing.JButton();
        InfoInter = new javax.swing.JLabel();
        Intercambiar = new javax.swing.JButton();
        VerListado = new javax.swing.JButton();
        TablaIntercambios = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTMostrar = new javax.swing.JTable();
        TotalSobres = new javax.swing.JLabel();
        TotalEstampasColocadas = new javax.swing.JLabel();
        AbrirNormal = new javax.swing.JButton();
        AbrirDorado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VerEstampas = new javax.swing.JButton();
        VerSobres = new javax.swing.JButton();
        MiAlbum = new javax.swing.JButton();
        ReportesUsuario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        RecienAbierto.setTitle("Sobre Abierto");
        RecienAbierto.setAutoRequestFocus(false);
        RecienAbierto.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Estampas Contenidas");

        MostrarEstampa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));

        Siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/derecha.jpg"))); // NOI18N
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        InformacionEstampa.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        InformacionEstampa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ColocarRecienAbierto.setFont(new java.awt.Font("BankGothic Md BT", 1, 12)); // NOI18N
        ColocarRecienAbierto.setText("Colocar Estampa");
        ColocarRecienAbierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColocarRecienAbiertoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RecienAbiertoLayout = new javax.swing.GroupLayout(RecienAbierto.getContentPane());
        RecienAbierto.getContentPane().setLayout(RecienAbiertoLayout);
        RecienAbiertoLayout.setHorizontalGroup(
            RecienAbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecienAbiertoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MostrarEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(RecienAbiertoLayout.createSequentialGroup()
                .addGroup(RecienAbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecienAbiertoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RecienAbiertoLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(ColocarRecienAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RecienAbiertoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(InformacionEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        RecienAbiertoLayout.setVerticalGroup(
            RecienAbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecienAbiertoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RecienAbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecienAbiertoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RecienAbiertoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(MostrarEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InformacionEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ColocarRecienAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        MostrarSyE.setTitle("Ver Sobres y Estampas");

        Sobres.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        Sobres.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 51), null));

        SobreSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/derecha.jpg"))); // NOI18N
        SobreSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreSiguienteActionPerformed(evt);
            }
        });

        SobreAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/izquierda.jpg"))); // NOI18N
        SobreAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreAnteriorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SOBRES");

        ImagenSobre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        EstampaSiguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/derecha.jpg"))); // NOI18N
        EstampaSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstampaSiguiente1ActionPerformed(evt);
            }
        });

        ColocarEstampa2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ColocarEstampa2.setText("Colocar Estampa");
        ColocarEstampa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColocarEstampa2ActionPerformed(evt);
            }
        });

        InformacionEstampa1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        InformacionEstampa1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout MostrarSyELayout = new javax.swing.GroupLayout(MostrarSyE.getContentPane());
        MostrarSyE.getContentPane().setLayout(MostrarSyELayout);
        MostrarSyELayout.setHorizontalGroup(
            MostrarSyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarSyELayout.createSequentialGroup()
                .addGroup(MostrarSyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MostrarSyELayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MostrarSyELayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(ImagenSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstampaSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MostrarSyELayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(ColocarEstampa2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(MostrarSyELayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(MostrarSyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MostrarSyELayout.createSequentialGroup()
                        .addComponent(InformacionEstampa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MostrarSyELayout.createSequentialGroup()
                        .addComponent(SobreAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sobres, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(SobreSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        MostrarSyELayout.setVerticalGroup(
            MostrarSyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarSyELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MostrarSyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SobreSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sobres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SobreAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MostrarSyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MostrarSyELayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ImagenSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MostrarSyELayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(EstampaSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InformacionEstampa1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ColocarEstampa2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        MostrarSoloEstampas.setTitle("Estampas");

        MostrarEstampa2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 204, 204), null, null));

        EstampaSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/derecha.jpg"))); // NOI18N
        EstampaSiguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 204, 255), null, null));
        EstampaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstampaSiguienteActionPerformed(evt);
            }
        });

        ColocarEstampa3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ColocarEstampa3.setText("Colocar Estampa");
        ColocarEstampa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColocarEstampa3ActionPerformed(evt);
            }
        });

        InformacionEstampa2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        InformacionEstampa2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MostrarSoloEstampasLayout = new javax.swing.GroupLayout(MostrarSoloEstampas.getContentPane());
        MostrarSoloEstampas.getContentPane().setLayout(MostrarSoloEstampasLayout);
        MostrarSoloEstampasLayout.setHorizontalGroup(
            MostrarSoloEstampasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarSoloEstampasLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(MostrarEstampa2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EstampaSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MostrarSoloEstampasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MostrarSoloEstampasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MostrarSoloEstampasLayout.createSequentialGroup()
                        .addComponent(ColocarEstampa3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MostrarSoloEstampasLayout.createSequentialGroup()
                        .addComponent(InformacionEstampa2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        MostrarSoloEstampasLayout.setVerticalGroup(
            MostrarSoloEstampasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarSoloEstampasLayout.createSequentialGroup()
                .addGroup(MostrarSoloEstampasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MostrarSoloEstampasLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(MostrarEstampa2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MostrarSoloEstampasLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(EstampaSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InformacionEstampa2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ColocarEstampa3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        AlbumUsuario.setTitle("Mi Album");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        MostrarJugadores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        NombreDeEquipos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        NombreDeEquipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreDeEquipos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        EquipoSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.jpg"))); // NOI18N
        EquipoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoSiguienteActionPerformed(evt);
            }
        });

        EquipoAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/izquierda1.png"))); // NOI18N
        EquipoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoAnteriorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("NOMBRE DEL EQUIPO");

        JugadorSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipod.png"))); // NOI18N
        JugadorSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorSiguienteActionPerformed(evt);
            }
        });

        JugadorAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipos.jpg"))); // NOI18N
        JugadorAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorAnteriorActionPerformed(evt);
            }
        });

        NombreDelJugador.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        NombreDelJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EquipoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(NombreDeEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addComponent(EquipoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(JugadorAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreDelJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MostrarJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JugadorSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreDeEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(EquipoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EquipoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(MostrarJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(JugadorSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(JugadorAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreDelJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AlbumUsuarioLayout = new javax.swing.GroupLayout(AlbumUsuario.getContentPane());
        AlbumUsuario.getContentPane().setLayout(AlbumUsuarioLayout);
        AlbumUsuarioLayout.setHorizontalGroup(
            AlbumUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AlbumUsuarioLayout.setVerticalGroup(
            AlbumUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        SobreDorado.setTitle("Sobre Dorado");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Contenido del Sobre Dorado");

        ImagenDorada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenDorada.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        InformacionDorada.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        InformacionDorada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InformacionDorada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SiguienteDorada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/derecha.jpg"))); // NOI18N
        SiguienteDorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteDoradaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setText("Agregar Estampa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(ImagenDorada, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(SiguienteDorada, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(InformacionDorada, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(ImagenDorada, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(SiguienteDorada, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InformacionDorada, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SobreDoradoLayout = new javax.swing.GroupLayout(SobreDorado.getContentPane());
        SobreDorado.getContentPane().setLayout(SobreDoradoLayout);
        SobreDoradoLayout.setHorizontalGroup(
            SobreDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SobreDoradoLayout.setVerticalGroup(
            SobreDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        EstampaInter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        InterSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipod.png"))); // NOI18N
        InterSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterSiguienteActionPerformed(evt);
            }
        });

        InfoInter.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        InfoInter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Intercambiar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Intercambiar.setText("InterCambiar");
        Intercambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntercambiarActionPerformed(evt);
            }
        });

        VerListado.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        VerListado.setText("Ver Listado");
        VerListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerListadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(Intercambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VerListado, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addComponent(EstampaInter, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(InterSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(InfoInter, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(EstampaInter, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(InterSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(InfoInter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Intercambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerListado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VentanaInterLayout = new javax.swing.GroupLayout(VentanaInter.getContentPane());
        VentanaInter.getContentPane().setLayout(VentanaInterLayout);
        VentanaInterLayout.setHorizontalGroup(
            VentanaInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaInterLayout.setVerticalGroup(
            VentanaInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        JTMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Jugador", "Equipo ", "Rareza", "Usuario "
            }
        ));
        JTMostrar.setRowHeight(30);
        jScrollPane1.setViewportView(JTMostrar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TablaIntercambiosLayout = new javax.swing.GroupLayout(TablaIntercambios.getContentPane());
        TablaIntercambios.getContentPane().setLayout(TablaIntercambiosLayout);
        TablaIntercambiosLayout.setHorizontalGroup(
            TablaIntercambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablaIntercambiosLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TablaIntercambiosLayout.setVerticalGroup(
            TablaIntercambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(50, 50));
        setMaximumSize(new java.awt.Dimension(600, 520));
        setMinimumSize(new java.awt.Dimension(600, 520));
        setPreferredSize(new java.awt.Dimension(600, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        TotalSobres.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TotalSobres.setForeground(new java.awt.Color(255, 255, 255));
        TotalSobres.setText("Sobres: ");
        getContentPane().add(TotalSobres);
        TotalSobres.setBounds(20, 40, 160, 30);

        TotalEstampasColocadas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TotalEstampasColocadas.setForeground(new java.awt.Color(255, 255, 255));
        TotalEstampasColocadas.setText("Estampas");
        getContentPane().add(TotalEstampasColocadas);
        TotalEstampasColocadas.setBounds(20, 70, 190, 20);

        AbrirNormal.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        AbrirNormal.setText("Abrir Normal");
        AbrirNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirNormalActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirNormal);
        AbrirNormal.setBounds(50, 160, 140, 40);

        AbrirDorado.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        AbrirDorado.setText("Abrir Dorado");
        AbrirDorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirDoradoActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirDorado);
        AbrirDorado.setBounds(370, 160, 140, 40);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sobres");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 160, 20);

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 3));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 560, 110);

        VerEstampas.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        VerEstampas.setText("Ver Estampas");
        VerEstampas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEstampasActionPerformed(evt);
            }
        });
        getContentPane().add(VerEstampas);
        VerEstampas.setBounds(350, 280, 160, 40);

        VerSobres.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        VerSobres.setText("Ver Sobres");
        VerSobres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerSobresActionPerformed(evt);
            }
        });
        getContentPane().add(VerSobres);
        VerSobres.setBounds(50, 280, 170, 40);

        MiAlbum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        MiAlbum.setText("Mi Album");
        MiAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiAlbumActionPerformed(evt);
            }
        });
        getContentPane().add(MiAlbum);
        MiAlbum.setBounds(50, 370, 160, 40);

        ReportesUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ReportesUsuario.setText("Reportes");
        ReportesUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(ReportesUsuario);
        ReportesUsuario.setBounds(350, 370, 170, 40);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 5));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 550, 240);

        NombreUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        NombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        NombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreUsuario.setText(activo.getUser());
        NombreUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));
        getContentPane().add(NombreUsuario);
        NombreUsuario.setBounds(190, 10, 200, 30);

        jButton7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(450, 20, 110, 30);

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton2.setText("Intercambios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 60, 119, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondousuario.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 590, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
        Login_Regis l1=new Login_Regis();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void AbrirNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirNormalActionPerformed
        MostrarEstampa.setText("");
        InformacionEstampa.setText("");
        VentanaUsuarios.actual=VentanaUsuarios.activo.sobres.CrearSobre();
        
        Integer abierto=VentanaUsuarios.activo.getAbiertos();
        abierto=abierto+1;
        VentanaUsuarios.activo.setAbiertos(abierto);
        this.TotalSobres.setText("Sobres Abiertos: "+VentanaUsuarios.activo.getAbiertos());
        
        RecienAbierto.setVisible(true);
        VentanaUsuarios.estampa=actual.listaEstampa.ObtenerPrimera();
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampa.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampa.getNombre());
        MostrarEstampa.setIcon(new ImageIcon(VentanaUsuarios.estampa.getRuta()));
        InformacionEstampa.setText("Nombre: "+VentanaUsuarios.estampa.getNombre()
        +" Posicion: "+VentanaUsuarios.jugador.getPosicion()+" Equipo: "+VentanaUsuarios.equipo.getNombre()+" Rareza: "
        +VentanaUsuarios.estampa.getRareza()+" Estampa No: "+VentanaUsuarios.estampa.getCantidad());
    }//GEN-LAST:event_AbrirNormalActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        
        VentanaUsuarios.estampa=VentanaUsuarios.actual.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampa);
        if(VentanaUsuarios.estampa==null){
            VentanaUsuarios.estampa=VentanaUsuarios.actual.listaEstampa.ObtenerPrimera();
        }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampa.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampa.getNombre());
        MostrarEstampa.setIcon(new ImageIcon(VentanaUsuarios.estampa.getRuta()));
        InformacionEstampa.setText("Nombre: "+VentanaUsuarios.estampa.getNombre()+" Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+" Equipo: "+VentanaUsuarios.equipo.getNombre()+" Rareza: "
        +VentanaUsuarios.estampa.getRareza()+" Estampa No: "+VentanaUsuarios.estampa.getCantidad());
    }//GEN-LAST:event_SiguienteActionPerformed
//----------------FALTA EL COMANDO PARA AGREGAR ESTAMPA----------
    
    //BOTON DE VER SOBRES
    private void VerSobresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerSobresActionPerformed
        MostrarSyE.setVisible(true);
        VentanaUsuarios.sobres=VentanaUsuarios.activo.sobres.ObtenerPrimero();
        Sobres.setText(sobres.getNumero()+"");
        VentanaUsuarios.estampas=VentanaUsuarios.sobres.listaEstampa.ObtenerPrimera();
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas.getNombre());
        
        ImagenSobre.setIcon(new ImageIcon(VentanaUsuarios.estampas.getRuta()));
         InformacionEstampa1.setText("Nombre: "+VentanaUsuarios.estampas.getNombre()+"- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"- Equipo: "+VentanaUsuarios.equipo.getNombre()+"- Rareza: "+
                 VentanaUsuarios.estampas.getRareza()+"-- Estampa No: "+VentanaUsuarios.estampas.getCantidad());
        
    }//GEN-LAST:event_VerSobresActionPerformed
//Paso al sobre siguiente;
    private void SobreSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreSiguienteActionPerformed
        VentanaUsuarios.sobres=VentanaUsuarios.activo.sobres.ObtenerSiguiente(VentanaUsuarios.sobres);
        Sobres.setText(sobres.getNumero()+"");
        VentanaUsuarios.estampas=VentanaUsuarios.sobres.listaEstampa.ObtenerPrimera();
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas.getNombre());
        
        ImagenSobre.setIcon(new ImageIcon(VentanaUsuarios.estampas.getRuta()));
         InformacionEstampa1.setText("Nombre: "+VentanaUsuarios.estampas.getNombre()+"- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"- Equipo: "+VentanaUsuarios.equipo.getNombre()+"- Rareza: "+
                 VentanaUsuarios.estampas.getRareza()+"- Estampa No: "+VentanaUsuarios.estampas.getCantidad());
    }//GEN-LAST:event_SobreSiguienteActionPerformed
//paso al sobre anterior;
    private void SobreAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreAnteriorActionPerformed
        VentanaUsuarios.sobres=VentanaUsuarios.activo.sobres.ObtenerAnterior(VentanaUsuarios.sobres);
        Sobres.setText(sobres.getNumero()+"");
        VentanaUsuarios.estampas=VentanaUsuarios.sobres.listaEstampa.ObtenerPrimera();
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas.getNombre());
        
        ImagenSobre.setIcon(new ImageIcon(VentanaUsuarios.estampas.getRuta()));
         InformacionEstampa1.setText("Nombre: "+VentanaUsuarios.estampas.getNombre()+"- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"- Equipo: "+VentanaUsuarios.equipo.getNombre()+"- Rareza: "+
                 VentanaUsuarios.estampas.getRareza()+"- Estampa No: "+VentanaUsuarios.estampas.getCantidad());
    }//GEN-LAST:event_SobreAnteriorActionPerformed
//Paso a la estampa siguiente;
    private void EstampaSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstampaSiguiente1ActionPerformed
      VentanaUsuarios.estampas=VentanaUsuarios.sobres.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampas);
      if(VentanaUsuarios.estampas==null){
          VentanaUsuarios.estampas=VentanaUsuarios.sobres.listaEstampa.ObtenerPrimera();
      }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas.getNombre());
        ImagenSobre.setIcon(new ImageIcon(VentanaUsuarios.estampas.getRuta()));
        InformacionEstampa1.setText("Nombre: "+VentanaUsuarios.estampas.getNombre()+"- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"- Equipo: "+VentanaUsuarios.equipo.getNombre()+"- Rareza: "+
                VentanaUsuarios.estampas.getRareza()+"- Estampa No: "+VentanaUsuarios.estampas.getCantidad());
    }//GEN-LAST:event_EstampaSiguiente1ActionPerformed
//Para ver solo estampas
    private void VerEstampasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEstampasActionPerformed
        VentanaUsuarios.sobres1=VentanaUsuarios.activo.sobres.ObtenerPrimero();
        VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerPrimera();
          VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas1.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas1.getNombre());
        MostrarEstampa2.setIcon(new ImageIcon(VentanaUsuarios.estampas1.getRuta()));
        InformacionEstampa2.setText("Nombre: "+VentanaUsuarios.estampas1.getNombre()+"- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"- Equipo: "+VentanaUsuarios.equipo.getNombre()+"- Rareza: "+
                VentanaUsuarios.estampas1.getRareza()+"- Estampa No: "+VentanaUsuarios.estampas1.getCantidad());
        MostrarSoloEstampas.setVisible(true);
        
    }//GEN-LAST:event_VerEstampasActionPerformed

    private void EstampaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstampaSiguienteActionPerformed

        VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampas1);
        if(VentanaUsuarios.estampas1==null){
            VentanaUsuarios.sobres1=VentanaUsuarios.activo.sobres.ObtenerSiguiente(VentanaUsuarios.sobres1);
            VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerPrimera();
        }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas1.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas1.getNombre());
        MostrarEstampa2.setIcon(new ImageIcon(VentanaUsuarios.estampas1.getRuta()));
        InformacionEstampa2.setText("Nombre: "+VentanaUsuarios.estampas1.getNombre()+"- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"- Equipo: "+VentanaUsuarios.equipo.getNombre()+"- Rareza: "+
                VentanaUsuarios.estampas1.getRareza()+"- Estampa No: "+VentanaUsuarios.estampas1.getCantidad());
        
        
    }//GEN-LAST:event_EstampaSiguienteActionPerformed
/*public static NodoSobre actual;
    public static Nodo_Estam estampa;
    public static String Ruta;
    public static String nombre;
    public static Integer Codigo;
    */
    private void ColocarRecienAbiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColocarRecienAbiertoActionPerformed
        String nombre1=VentanaUsuarios.estampa.getNombre();
        String codigo=VentanaUsuarios.estampa.getCodigo();
        String ruta=VentanaUsuarios.estampa.getRuta();
        Integer noEstampa=VentanaUsuarios.estampa.getCantidad();
        if(VentanaUsuarios.activo.equipos.ComprobrarExistencia(codigo, nombre1, ruta)){
            JOptionPane.showMessageDialog(null, "La Extampa Ya ha sido pegada");
        }else{
        VentanaUsuarios.activo.equipos.InsertarEstampa(codigo, nombre1, ruta);
        VentanaUsuarios.actual.listaEstampa.EliminarEstampa(nombre1,noEstampa);
        JOptionPane.showMessageDialog(null, "La estampa ha sido colocada en el album");
        
        //Para hacer el conteo de las estampas colocadas 
        Integer colocada=VentanaUsuarios.activo.getColocadas();
        colocada=colocada+1;
        VentanaUsuarios.activo.setColocadas(colocada);
        
        
        this.TotalEstampasColocadas.setText("Estampas Colocadas: "+VentanaUsuarios.activo.getColocadas());
        
        //para hacer el conteo de las veces que se ha colocado una estampa
        NodoAdmin aux=ListasGenerales.listaEstampas.ObtenerEstampa(nombre1, codigo);
        Integer colocada1=aux.getColocada();
        colocada1++;
        aux.setColocada(colocada1);
        
        VentanaUsuarios.estampa=VentanaUsuarios.actual.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampa);
        }
          if(VentanaUsuarios.estampa==null){
            VentanaUsuarios.estampa=VentanaUsuarios.actual.listaEstampa.ObtenerPrimera();
        }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampa.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampa.getNombre());
        MostrarEstampa.setIcon(new ImageIcon(VentanaUsuarios.estampa.getRuta()));
        InformacionEstampa.setText("Nombre: "+VentanaUsuarios.estampa.getNombre()+"-- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"-- Equipo: "+VentanaUsuarios.equipo.getNombre()+"-- Rareza: "
        +VentanaUsuarios.estampa.getRareza()+"-- Estampa No: "+VentanaUsuarios.estampa.getCantidad());
        
    }//GEN-LAST:event_ColocarRecienAbiertoActionPerformed

    private void ColocarEstampa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColocarEstampa2ActionPerformed
        String nombre1=VentanaUsuarios.estampas.getNombre();
        String codigo=VentanaUsuarios.estampas.getCodigo();
        String ruta=VentanaUsuarios.estampas.getRuta();
        Integer noEstampa=VentanaUsuarios.estampas.getCantidad();
        if(VentanaUsuarios.activo.equipos.ComprobrarExistencia(codigo, nombre1, ruta)){
            JOptionPane.showMessageDialog(null,"La estampa Ya ha sido Pegada");
        }else{
        VentanaUsuarios.activo.equipos.InsertarEstampa(codigo, nombre1, ruta);
        VentanaUsuarios.sobres.listaEstampa.EliminarEstampa(nombre1,noEstampa);
        JOptionPane.showMessageDialog(null, "La estampa ha sido colocada en el album");
        
        //Para hacer el conteo de las estampas colocadas 
        Integer colocada=VentanaUsuarios.activo.getColocadas();
        colocada=colocada+1;
        VentanaUsuarios.activo.setColocadas(colocada);
        this.TotalEstampasColocadas.setText("Estampas Colocadas: "+VentanaUsuarios.activo.getColocadas());
        
        //para hacer el conteo de cuantas veces se ha colocado
      NodoAdmin aux=ListasGenerales.listaEstampas.ObtenerEstampa(nombre1, codigo);
        Integer colocada1=aux.getColocada();
        colocada1++;
        aux.setColocada(colocada1);
        
        VentanaUsuarios.estampas=VentanaUsuarios.sobres.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampas);
        }
          if(VentanaUsuarios.estampas==null){
            VentanaUsuarios.estampas=VentanaUsuarios.sobres.listaEstampa.ObtenerPrimera();
        }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas.getNombre());
        ImagenSobre.setIcon(new ImageIcon(VentanaUsuarios.estampas.getRuta()));
        InformacionEstampa1.setText("Nombre: "+VentanaUsuarios.estampas.getNombre()+"-- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"-- Equipo: "+VentanaUsuarios.equipo.getNombre()+"-- Rareza: "
        +VentanaUsuarios.estampas.getRareza()+"-- Estampa No: "+VentanaUsuarios.estampas.getCantidad());
        
    }//GEN-LAST:event_ColocarEstampa2ActionPerformed

    private void ColocarEstampa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColocarEstampa3ActionPerformed
        String nombre1=VentanaUsuarios.estampas1.getNombre();
        String codigo=VentanaUsuarios.estampas1.getCodigo();
        String ruta=VentanaUsuarios.estampas1.getRuta();
        Integer noEstampa=VentanaUsuarios.estampas1.getCantidad();
        if(VentanaUsuarios.activo.equipos.ComprobrarExistencia(codigo, nombre1, ruta)){
            JOptionPane.showMessageDialog(null,"La estampa Ya ha sido Pegada");
        }else{
        VentanaUsuarios.activo.equipos.InsertarEstampa(codigo, nombre1, ruta);
        VentanaUsuarios.sobres1.listaEstampa.EliminarEstampa(nombre1,noEstampa);
        JOptionPane.showMessageDialog(null, "La estampa ha sido colocada en el album");
        
        //Para hacer el conteo de las estampas colocadas 
        Integer colocada=VentanaUsuarios.activo.getColocadas();
        colocada=colocada+1;
        VentanaUsuarios.activo.setColocadas(colocada);
        this.TotalEstampasColocadas.setText("Estampas Colocadas: "+VentanaUsuarios.activo.getColocadas());
        
        //para hacer el conteo de las veces qe se ha colocado una estampa
        NodoAdmin aux=ListasGenerales.listaEstampas.ObtenerEstampa(nombre1, codigo);
        Integer colocada1=aux.getColocada();
        colocada1++;
        aux.setColocada(colocada1);
        
        VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampas1);
        }
          if(VentanaUsuarios.estampas1==null){
              VentanaUsuarios.sobres1=VentanaUsuarios.activo.sobres.ObtenerSiguiente(VentanaUsuarios.sobres1);
            VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerPrimera();
        }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas1.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas1.getNombre());
        MostrarEstampa2.setIcon(new ImageIcon(VentanaUsuarios.estampas1.getRuta()));
        InformacionEstampa2.setText("Nombre: "+VentanaUsuarios.estampas1.getNombre()+"-- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"-- Equipo: "+VentanaUsuarios.equipo.getNombre()+"-- Rareza: "
        +VentanaUsuarios.estampas1.getRareza()+"-- Estampa No: "+VentanaUsuarios.estampas1.getCantidad());
    }//GEN-LAST:event_ColocarEstampa3ActionPerformed

    private void MiAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiAlbumActionPerformed
        
        this.AlbumUsuario.setVisible(true);
        VentanaUsuarios.equipos=VentanaUsuarios.activo.equipos.ObtenerPrimero();
        VentanaUsuarios.jugadores1=VentanaUsuarios.equipos.jugadores.ObtenerPrimero();
        //Guardando los datos para mostrar;
        
        VentanaUsuarios.nombreEquipo=VentanaUsuarios.equipos.getNombre();
        VentanaUsuarios.nombreJugador=VentanaUsuarios.jugadores1.getNombre();
        VentanaUsuarios.imagen=VentanaUsuarios.jugadores1.getRuta();
        
        if(VentanaUsuarios.imagen==null || VentanaUsuarios.imagen.equals("")){
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setText("La estampa no se ha encontrado");
            this.MostrarJugadores.setIcon(new ImageIcon());
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }else{
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setText("");
            this.MostrarJugadores.setIcon(new ImageIcon(VentanaUsuarios.imagen));
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }
    }//GEN-LAST:event_MiAlbumActionPerformed

    private void EquipoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoSiguienteActionPerformed
        VentanaUsuarios.equipos=VentanaUsuarios.activo.equipos.ObtenerSiguientes(VentanaUsuarios.equipos);
        VentanaUsuarios.jugadores1=VentanaUsuarios.equipos.jugadores.ObtenerPrimero();
        //Para mostrar
        VentanaUsuarios.nombreEquipo=VentanaUsuarios.equipos.getNombre();
       VentanaUsuarios.nombreJugador=VentanaUsuarios.jugadores1.getNombre();
        VentanaUsuarios.imagen=VentanaUsuarios.jugadores1.getRuta();
        if(VentanaUsuarios.imagen==null || VentanaUsuarios.imagen.equals("")){
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setText("La estampa no se ha encontrado");
            this.MostrarJugadores.setIcon(new ImageIcon());
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }else{
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setText("");
            this.MostrarJugadores.setIcon(new ImageIcon(VentanaUsuarios.imagen));
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }
    }//GEN-LAST:event_EquipoSiguienteActionPerformed

    private void EquipoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoAnteriorActionPerformed
        VentanaUsuarios.equipos=VentanaUsuarios.activo.equipos.ObtenerAnterior(VentanaUsuarios.equipos);
        VentanaUsuarios.jugadores1=VentanaUsuarios.equipos.jugadores.ObtenerPrimero();
        //Para mostrar
        VentanaUsuarios.nombreEquipo=VentanaUsuarios.equipos.getNombre();
       VentanaUsuarios.nombreJugador=VentanaUsuarios.jugadores1.getNombre();
        VentanaUsuarios.imagen=VentanaUsuarios.jugadores1.getRuta();
        if(VentanaUsuarios.imagen==null || VentanaUsuarios.imagen.equals("")){
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setIcon(new ImageIcon());
            this.MostrarJugadores.setText("La estampa no se ha encontrado");
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }else{
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setText("");
            this.MostrarJugadores.setIcon(new ImageIcon(VentanaUsuarios.imagen));
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }
    }//GEN-LAST:event_EquipoAnteriorActionPerformed

    private void JugadorSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorSiguienteActionPerformed
        VentanaUsuarios.jugadores1=VentanaUsuarios.equipos.jugadores.ObtenerSiguientes(VentanaUsuarios.jugadores1);
        //Para mostrar
        VentanaUsuarios.nombreEquipo=VentanaUsuarios.equipos.getNombre();
        VentanaUsuarios.nombreJugador=VentanaUsuarios.jugadores1.getNombre();
        VentanaUsuarios.imagen=VentanaUsuarios.jugadores1.getRuta();
        if(VentanaUsuarios.imagen==null || VentanaUsuarios.imagen.equals("")){
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setIcon(new ImageIcon());
            this.MostrarJugadores.setText("La estampa no se ha encontrado");
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }else{
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setText("");
            this.MostrarJugadores.setIcon(new ImageIcon(VentanaUsuarios.imagen));
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }
    }//GEN-LAST:event_JugadorSiguienteActionPerformed

    private void JugadorAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorAnteriorActionPerformed
        VentanaUsuarios.jugadores1=VentanaUsuarios.equipos.jugadores.ObtenerAnterior(VentanaUsuarios.jugadores1);
        
        VentanaUsuarios.nombreEquipo=VentanaUsuarios.equipos.getNombre();
        VentanaUsuarios.nombreJugador=VentanaUsuarios.jugadores1.getNombre();
        VentanaUsuarios.imagen=VentanaUsuarios.jugadores1.getRuta();
        if(VentanaUsuarios.imagen==null || VentanaUsuarios.imagen.equals("")){
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setIcon(new ImageIcon());
            this.MostrarJugadores.setText("La estampa no se ha encontrado");
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }else{
            this.NombreDeEquipos.setText(VentanaUsuarios.nombreEquipo);
            this.MostrarJugadores.setText("");
            this.MostrarJugadores.setIcon(new ImageIcon(VentanaUsuarios.imagen));
            this.NombreDelJugador.setText(VentanaUsuarios.nombreJugador);
        }
    }//GEN-LAST:event_JugadorAnteriorActionPerformed

    private void AbrirDoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirDoradoActionPerformed
      
        VentanaUsuarios.actual=VentanaUsuarios.activo.sobres.CrearSobreDorado();
        Integer abierto=VentanaUsuarios.activo.getAbiertos();
        abierto=abierto+1;
        VentanaUsuarios.activo.setAbiertos(abierto);
        this.TotalSobres.setText("Sobres Abiertos: "+VentanaUsuarios.activo.getAbiertos());
        this.SobreDorado.setVisible(true);
          
        VentanaUsuarios.estampa=actual.listaEstampa.ObtenerPrimera();
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampa.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampa.getNombre());
        this.ImagenDorada.setIcon(new ImageIcon(VentanaUsuarios.estampa.getRuta()));
        this.InformacionDorada.setText("Nombre: "+VentanaUsuarios.estampa.getNombre()
        +"- Posicion: "+VentanaUsuarios.jugador.getPosicion()+"- Equipo:"+VentanaUsuarios.equipo.getNombre()+
                "- Rareza:"
        +VentanaUsuarios.estampa.getRareza()+"-Estampa no:"+VentanaUsuarios.estampa.getCantidad());
        
    }//GEN-LAST:event_AbrirDoradoActionPerformed

    private void SiguienteDoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteDoradaActionPerformed
        VentanaUsuarios.estampa=VentanaUsuarios.actual.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampa);
        if(VentanaUsuarios.estampa==null){
            VentanaUsuarios.estampa=VentanaUsuarios.actual.listaEstampa.ObtenerPrimera();
        }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampa.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampa.getNombre());
        this.ImagenDorada.setIcon(new ImageIcon(VentanaUsuarios.estampa.getRuta()));
        this.InformacionDorada.setText("Nombre: "+VentanaUsuarios.estampa.getNombre()+" Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+" Equipo: "+VentanaUsuarios.equipo.getNombre()+" Rareza: "
        +VentanaUsuarios.estampa.getRareza()+" Estampa No: "+VentanaUsuarios.estampa.getCantidad());
    }//GEN-LAST:event_SiguienteDoradaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre1=VentanaUsuarios.estampa.getNombre();
        String codigo=VentanaUsuarios.estampa.getCodigo();
        String ruta=VentanaUsuarios.estampa.getRuta();
        Integer noEstampa=VentanaUsuarios.estampa.getCantidad();
        if(VentanaUsuarios.activo.equipos.ComprobrarExistencia(codigo, nombre1, ruta)){
            JOptionPane.showMessageDialog(null, "La Extampa Ya ha sido pegada");
        }else{
        VentanaUsuarios.activo.equipos.InsertarEstampa(codigo, nombre1, ruta);
        VentanaUsuarios.actual.listaEstampa.EliminarEstampa(nombre1,noEstampa);
        JOptionPane.showMessageDialog(null, "La estampa ha sido colocada en el album");
        
        //Para hacer el conteo de las estampas colocadas 
        Integer colocada=VentanaUsuarios.activo.getColocadas();
        colocada=colocada+1;
        VentanaUsuarios.activo.setColocadas(colocada);
        this.TotalEstampasColocadas.setText("Estampas Colocadas: "+VentanaUsuarios.activo.getColocadas());
        
        //para hacer el conteo de las estampas colocada;
     NodoAdmin aux=ListasGenerales.listaEstampas.ObtenerEstampa(nombre1, codigo);
        Integer colocada1=aux.getColocada();
        colocada1++;
        aux.setColocada(colocada1);
        
        
        VentanaUsuarios.estampa=VentanaUsuarios.actual.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampa);
        }
          if(VentanaUsuarios.estampa==null){
            VentanaUsuarios.estampa=VentanaUsuarios.actual.listaEstampa.ObtenerPrimera();
        }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampa.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampa.getNombre());
        MostrarEstampa.setIcon(new ImageIcon(VentanaUsuarios.estampa.getRuta()));
        InformacionEstampa.setText("Nombre: "+VentanaUsuarios.estampa.getNombre()+"-- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"-- Equipo: "+VentanaUsuarios.equipo.getNombre()+"-- Rareza: "
        +VentanaUsuarios.estampa.getRareza()+"-- Estampa No: "+VentanaUsuarios.estampa.getCantidad());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaUsuarios.sobres1=VentanaUsuarios.activo.sobres.ObtenerPrimero();
        VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerPrimera();
          VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas1.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas1.getNombre());
        this.EstampaInter.setIcon(new ImageIcon(VentanaUsuarios.estampas1.getRuta()));
        this.InfoInter.setText("Nombre: "+VentanaUsuarios.estampas1.getNombre()+"- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"- Equipo: "+VentanaUsuarios.equipo.getNombre()+"- Rareza: "+
                VentanaUsuarios.estampas1.getRareza()+"- Estampa No: "+VentanaUsuarios.estampas1.getCantidad());
        this.VentanaInter.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void InterSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterSiguienteActionPerformed
        
        
        VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampas1);
        if(VentanaUsuarios.estampas1==null){
            VentanaUsuarios.sobres1=VentanaUsuarios.activo.sobres.ObtenerSiguiente(VentanaUsuarios.sobres1);
            VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerPrimera();
        }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas1.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas1.getNombre());
        this.EstampaInter.setIcon(new ImageIcon(VentanaUsuarios.estampas1.getRuta()));
        this.InfoInter.setText("Nombre: "+VentanaUsuarios.estampas1.getNombre()+"- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"- Equipo: "+VentanaUsuarios.equipo.getNombre()+"- Rareza: "+
                VentanaUsuarios.estampas1.getRareza()+"- Estampa No: "+VentanaUsuarios.estampas1.getCantidad());
        
      
        
        
    }//GEN-LAST:event_InterSiguienteActionPerformed

    private void IntercambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntercambiarActionPerformed
        String nombre1=VentanaUsuarios.estampas1.getNombre();
        String codigo=VentanaUsuarios.estampas1.getCodigo();
        
        Integer noEstampa=VentanaUsuarios.estampas1.getCantidad();
        Integer rareza=VentanaUsuarios.estampas1.getRareza();
        Nodo_Equipo tem=ListasGenerales.listaEquipo.ObtenerEquipo(codigo);
        String nombreUser=VentanaUsuarios.activo.getUser();
        String nombreE=tem.getNombre();
        
        
        VentanaUsuarios.sobres1.listaEstampa.EliminarEstampa(nombre1,noEstampa);
        JOptionPane.showMessageDialog(null, "La estampa ha sido Colocada en los intercambios");
        ListasGenerales.listaCambios.Intercambiar(nombre1, nombreE, rareza,nombreUser );
        
        
        VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerSiguiente(VentanaUsuarios.estampas1);
        
          if(VentanaUsuarios.estampas1==null){
              VentanaUsuarios.sobres1=VentanaUsuarios.activo.sobres.ObtenerSiguiente(VentanaUsuarios.sobres1);
            VentanaUsuarios.estampas1=VentanaUsuarios.sobres1.listaEstampa.ObtenerPrimera();
        }
        VentanaUsuarios.equipo=VentanaUsuarios.activo.equipos.ObtenerEquipo(VentanaUsuarios.estampas1.getCodigo());
        VentanaUsuarios.jugador=VentanaUsuarios.equipo.jugadores.ObtenerJ(VentanaUsuarios.estampas1.getNombre());
        MostrarEstampa2.setIcon(new ImageIcon(VentanaUsuarios.estampas1.getRuta()));
        InformacionEstampa2.setText("Nombre: "+VentanaUsuarios.estampas1.getNombre()+"-- Posicion: "
                +VentanaUsuarios.jugador.getPosicion()+"-- Equipo: "+VentanaUsuarios.equipo.getNombre()+"-- Rareza: "
        +VentanaUsuarios.estampas1.getRareza()+"-- Estampa No: "+VentanaUsuarios.estampas1.getCantidad());
        
    }//GEN-LAST:event_IntercambiarActionPerformed

    private void VerListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerListadoActionPerformed
        this.VentanaInter.setVisible(true);
        this.TablaIntercambios.setVisible(true);
        MostrarTabla();
    }//GEN-LAST:event_VerListadoActionPerformed

    private void ReportesUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesUsuarioActionPerformed
        try {
            ReportesUsuarios u1=new ReportesUsuarios();
        } catch (IOException ex) {
            Logger.getLogger(VentanaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReportesUsuarioActionPerformed
  public void MostrarTabla(){
      String tabla[][]=new String[ListasGenerales.listaCambios.ObtenerTama()][4];
      NodoCambio aux=ListasGenerales.listaCambios.ObtenerPrimero();
      for(int j=0;j<ListasGenerales.listaCambios.ObtenerTama();j++){
          tabla[j][0]=aux.getNombre();
          tabla[j][1]=aux.getEquipo();
          tabla[j][2]=Integer.toString(aux.getRara());
          tabla[j][3]=aux.getUser();
          aux=ListasGenerales.listaCambios.ObtenerSiguiente(aux);
      }
      
       JTMostrar.setModel(new javax.swing.table.DefaultTableModel(
            tabla,
            new String [] {
                "Nombre Jugador", "Equipo ", "Rareza", "Usuario "
            }
        ));
      
  }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuarios(activo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirDorado;
    private javax.swing.JButton AbrirNormal;
    private javax.swing.JFrame AlbumUsuario;
    private javax.swing.JButton ColocarEstampa2;
    private javax.swing.JButton ColocarEstampa3;
    private javax.swing.JButton ColocarRecienAbierto;
    private javax.swing.JButton EquipoAnterior;
    private javax.swing.JButton EquipoSiguiente;
    private javax.swing.JLabel EstampaInter;
    private javax.swing.JButton EstampaSiguiente;
    private javax.swing.JButton EstampaSiguiente1;
    private javax.swing.JLabel ImagenDorada;
    private javax.swing.JLabel ImagenSobre;
    private javax.swing.JLabel InfoInter;
    private javax.swing.JLabel InformacionDorada;
    private javax.swing.JLabel InformacionEstampa;
    private javax.swing.JLabel InformacionEstampa1;
    private javax.swing.JLabel InformacionEstampa2;
    private javax.swing.JButton InterSiguiente;
    private javax.swing.JButton Intercambiar;
    private javax.swing.JTable JTMostrar;
    private javax.swing.JButton JugadorAnterior;
    private javax.swing.JButton JugadorSiguiente;
    private javax.swing.JButton MiAlbum;
    private javax.swing.JLabel MostrarEstampa;
    private javax.swing.JLabel MostrarEstampa2;
    private javax.swing.JLabel MostrarJugadores;
    private javax.swing.JDialog MostrarSoloEstampas;
    private javax.swing.JDialog MostrarSyE;
    private javax.swing.JLabel NombreDeEquipos;
    private javax.swing.JLabel NombreDelJugador;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JDialog RecienAbierto;
    private javax.swing.JButton ReportesUsuario;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton SiguienteDorada;
    private javax.swing.JButton SobreAnterior;
    private javax.swing.JDialog SobreDorado;
    private javax.swing.JButton SobreSiguiente;
    private javax.swing.JLabel Sobres;
    private javax.swing.JFrame TablaIntercambios;
    private javax.swing.JLabel TotalEstampasColocadas;
    private javax.swing.JLabel TotalSobres;
    private javax.swing.JFrame VentanaInter;
    private javax.swing.JButton VerEstampas;
    private javax.swing.JButton VerListado;
    private javax.swing.JButton VerSobres;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
