/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presencial;

import javax.swing.JOptionPane;

/**
 *
 * @author feliciano07
 */
public class Ventana extends javax.swing.JFrame {
     public String nombre;
     public String telefono;
     public String direccion;
     public static ListaAgenda lista;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setVisible(true);
        Ventana.lista=new ListaAgenda();
        //lista=new ListaAgenda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Jtelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jdireccion = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar");
        setBackground(new java.awt.Color(153, 255, 255));
        setMaximumSize(new java.awt.Dimension(594, 439));
        setMinimumSize(new java.awt.Dimension(594, 439));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(Jnombre);
        Jnombre.setBounds(20, 50, 410, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 100, 20);

        Jtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(Jtelefono);
        Jtelefono.setBounds(20, 130, 210, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Telefono");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 180, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Direccion");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 190, 40);
        getContentPane().add(Jdireccion);
        Jdireccion.setBounds(30, 220, 390, 30);

        agregar.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(380, 310, 140, 40);

        mostrar.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(mostrar);
        mostrar.setBounds(70, 310, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtelefonoActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        nombre=Jnombre.getText();
        telefono=Jtelefono.getText();
        direccion=Jdireccion.getText();
        Ventana.lista.Agregar(nombre, telefono, direccion);
        JOptionPane.showMessageDialog(null, "El contacto se ha agregado");
        Jnombre.setText("");
        Jtelefono.setText("");
        Jdireccion.setText("");
          
    }//GEN-LAST:event_agregarActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        Ventana.lista.Listar();
        Mostrar m1=new Mostrar();
        
        
        
        
        
        
    }//GEN-LAST:event_mostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jdireccion;
    private javax.swing.JTextField Jnombre;
    private javax.swing.JTextField Jtelefono;
    private javax.swing.JButton agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mostrar;
    // End of variables declaration//GEN-END:variables
}
